stages:
  - build
  - test
  - deploy

release_gnu5:
  stage: build
  script:
    - source util/commit.sh release_gnu5 1
  tags:
    - avro-commit

release_gnu6:
  stage: build
  script:
    - source util/commit.sh release_gnu6 1
  tags:
    - avro-commit

release_gnu7:
  stage: build
  script:
    - source util/commit.sh release_gnu7 1
  tags:
    - avro-commit

release_clang:
  stage: build
  script:
    - source util/commit.sh release_clang 1
  tags:
    - avro-commit

release_tests:
  stage: test
  script:
    - source util/commit.sh release_gnu7 4
    - cd build/release_gnu7
    - Xvfb :5 -screen 0 1280x1280x24 &
    - export DISPLAY=:5
    - make unit
  tags:
    - avro-commit

coverage_tests:
  stage: test
  script:
    - source util/commit.sh coverage_gnu5 6
    - cp -r build/coverage_gnu5/avro_coverage_html coverage_results
  artifacts:
    paths:
      - coverage_results
  tags:
    - avro-commit

pages:
  stage: deploy
  script:
    - mv coverage_results public
  artifacts:
    paths:
    - public
