stages:
  - build
  - test
  - deploy

release_gnu5:
  stage: build
  script:
    - source util/commit.sh release_gnu5
  tags:
    - avro-commit

release_gnu6:
  stage: build
  script:
    - source util/commit.sh release_gnu6
  tags:
    - avro-commit

release_gnu7:
  stage: build
  script:
    - source util/commit.sh release_gnu7
  tags:
    - avro-commit

release_clang:
  stage: build
  script:
    - source util/commit.sh release_clang
  tags:
    - avro-commit

release_tests:
  stage: test
  script:
    - source util/commit.sh release_gnu7
    - cd build/release_gnu7
    - make unit
  tags:
    - avro-commit

coverage_tests:
  stage: test
  script:
    - source util/commit.sh coverage_gnu5
    - cp -r build/coverage_gnu5/avroCoverageHTML coverage_results
  artifacts:
    paths:
      - coverage_results
  tags:
    - avro-commit

pages:
  stage: deploy
  script:
    - mv coverage_results public
  artifacts:
    paths:
    - public
