stages:
  - build
  - test
  - deploy

release_gnu5:
  stage: build
  script:
    - source util/commit.sh release_gnu5 6
  tags:
    - avro-commit

release_gnu6:
  stage: build
  script:
    - source util/commit.sh release_gnu6 6
  tags:
    - avro-commit


release_gnu7:
  stage: build
  script:
    - source util/commit.sh release_gnu7 6
  tags:
    - avro-commit

release_clang:
  stage: build
  script:
    - source util/commit.sh release_clang 6
  tags:
    - avro-commit

release_tests:
  stage: test
  script:
    - source util/commit.sh release_gnu7 4
    - cd build/release_gnu7
    - Xvfb :6 -screen 0 1280x1280x24 &
    - export DISPLAY=:6
    - make unit
    - cd ../../
    - mkdir unit_test_output
    - mv build/release_gnu7/unit_tests.out unit_test_output
  tags:
    - avro-commit
  artifacts:
    paths:
      - unit_test_output

coverage_tests:
  stage: test
  script:
    #- Xvfb :5 -screen 0 1280x1280x24 &
    #- export DISPLAY=:5
    - source util/commit.sh coverage_gnu5 6
    - cp -r build/coverage_gnu5/avro_coverage_html coverage_results
    - mkdir unit_test_output
    - mv build/coverage_gnu5/unit_tests.out unit_test_output
  artifacts:
    paths:
      - coverage_results
      - unit_test_output
  tags:
    - avro-commit

regression_tests:
  only: schedules
  stage: test
  script:
    - source util/commit.sh release_gnu7 6
    - mkdir -p regression_results
    - cd regression_results
    - ../test/regression/benchmark3d.sh ../build/release_gnu7/bin/avro ../test/library/ .
  artifacts:
    paths:
      - regression_results
  tags:
    - avro_commit

pages:
  stage: deploy
  script:
    - mv coverage_results public
  artifacts:
    paths:
    - public
