stages:
  - build
  - test

release_gnu5:
  stage: build
  script:
    - source util/commit.sh release_gnu5
  tags:
    - avro-commit

release_gnu6:
  stage: build
  script:
    - source util/commit.sh release_gnu6
  tags:
    - avro-commit

release_gnu7:
  stage: build
  script:
    - source util/commit.sh release_gnu7
  tags:
    - avro-commit

release_clang:
  stage: build
  script:
    - source util/commit.sh release_clang
  tags:
    - avro-commit

unit_tests:
  stage: test
  script:
    - source util/commit.sh release_gnu7
    - cd build/release_gnu7
    - make unit
  tags:
    - avro-commit

coverage_test:
  stage: test
  script:
    - source util/commit.sh coverage_gnu5
    - cp -r build/coverage_gnu5/avroCoverageHTML coverage_results
    - cp cmake/coverage-prolog.html coverage_results/index.html
  only:
    - merge_requests
  artifacts:
    paths:
      - coverage_results
  tags:
    - avro-commit

# the coverage test job
job-coverage:
  stage: none
  script:
    - export ESP_DIR=/home/gitlab-runner/Codes/EngSketchPad
    - export CAS_DIR=/home/gitlab-runner/Codes/OpenCASCADE-7.3.1
    - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$CAS_DIR/lib
    - mkdir build
    - mkdir build/coverage
    - cd build/coverage
    - cmake ../../
    - make -j12
    # need these tests to be shorter...
    #- make unit_coverage
    #- make coverage_info
    - cd ../../
    # - cp -r build/coverage/avroCoverageHTML coverage_results
    # remove this when it actually works!
    - mkdir coverage_results
    - cp cmake/coverage-prolog.html coverage_results/index.html
  artifacts:
    paths:
      - coverage_results
  tags:
    - avro-commit
