// Solution Adaptive Numerical Simulator (SANS)
// Copyright 2013-2019, Massachusetts Institute of Technology
// Licensed under The GNU Lesser General Public License, version 2.1
// See http://www.opensource.org/licenses/lgpl-2.1.php

#define MATRIXS_ELEMENTARYREFLECTOR_INSTANTIATE
#include "ElementaryReflector_impl.h"

namespace SANS
{
namespace DLA
{

INSTANCE_APPLY(1,1,Real)
INSTANCE_APPLY(1,2,Real)
INSTANCE_APPLY(1,3,Real)
INSTANCE_APPLY(1,4,Real)
INSTANCE_APPLY(1,5,Real)
INSTANCE_APPLY(1,6,Real)
INSTANCE_APPLY(1,7,Real)

INSTANCE_APPLY(2,1,Real)
INSTANCE_APPLY(2,2,Real)
INSTANCE_APPLY(2,3,Real)
INSTANCE_APPLY(2,4,Real)
INSTANCE_APPLY(2,5,Real)
INSTANCE_APPLY(2,6,Real)
INSTANCE_APPLY(2,7,Real)

INSTANCE_APPLY(3,1,Real)
INSTANCE_APPLY(3,2,Real)
INSTANCE_APPLY(3,3,Real)
INSTANCE_APPLY(3,4,Real)
INSTANCE_APPLY(3,5,Real)
INSTANCE_APPLY(3,6,Real)
INSTANCE_APPLY(3,7,Real)

INSTANCE_APPLY(4,3,Real)
INSTANCE_APPLY(4,4,Real)
INSTANCE_APPLY(4,5,Real)
INSTANCE_APPLY(4,6,Real)
INSTANCE_APPLY(4,7,Real)

INSTANCE_APPLY(5,4,Real)
INSTANCE_APPLY(5,5,Real)
INSTANCE_APPLY(5,6,Real)
INSTANCE_APPLY(5,7,Real)

INSTANCE_APPLY(6,5,Real)
INSTANCE_APPLY(6,6,Real)
INSTANCE_APPLY(6,7,Real)

INSTANCE_APPLY(7,6,Real)
INSTANCE_APPLY(7,7,Real)

INSTANCE_REFLECTOR( 1,Real )
INSTANCE_REFLECTOR( 2,Real )
INSTANCE_REFLECTOR( 3,Real )
INSTANCE_REFLECTOR( 4,Real )
INSTANCE_REFLECTOR( 5,Real )
INSTANCE_REFLECTOR( 6,Real )
INSTANCE_REFLECTOR( 7,Real )


}
}
