if (AVRO_WITH_MPI AND MPI_CXX_FOUND)
    set(USE_MPI TRUE )
    message( STATUS "found MPI ${MPI_CXX_COMPILER}" )
    add_definitions( -DAVRO_MPI )
    include_directories( SYSTEM ${MPI_CXX_INCLUDE_PATH} )

    # set the MPI_COMMAND
    if (NOT DEFINED _MPIEXEC_MAX_NUMPROCS_INIT)
        set( MPIEXEC_MAX_NUMPROCS 4 CACHE STRING "number of processors for unit testing" FORCE )
    endif()
    macro( RUN_WITH_MPIEXEC NUMPROCS )
        set( _MPIEXEC_MAX_NUMPROCS_INIT TRUE CACHE INTERNAL "" )
        set( MPI_COMMAND ${MPIEXEC} --hostfile tmp/hostfile ${MPIEXEC_NUMPROC_FLAG} ${NUMPROCS} )
    endmacro()
else()
    message( STATUS "MPI not found" )
    set(USE_MPI FALSE)
    macro( RUN_WITH_MPIEXEC )
    endmacro()
endif()
