set( BLAS_LIBRARIES blas )
if( APPLE )
    # OSX provides the lapack library in the Accelerate framewwork
    find_library(LAPACK_LIBRARIES NAMES Accelerate )
    find_path(LAPACKE_INCLUDE_DIRS Accelerate/Accelerate.h)
    add_definitions( -DLAPACK_ACCELERATE )
else()     
    find_package( lapack QUIET )
    if (NOT ${lapack_FOUND})
	message(STATUS "lapack not found")
	if ( EXISTS $ENV{LAPACK_DIR}/SRC/liblapack.a )
		set( LAPACK_LIBRARIES $ENV{LAPACK_DIR}/SRC/liblapack.a $ENV{LAPACK_DIR}/F2CLIBS/libf2c/libf2c.a )
        	set( BLAS_LIBRARIES  $ENV{LAPACK_DIR}/BLAS/SRC/libblas.a )
		#add_definitions(-DAVRO_NO_LAPACK)
    	else()
    		find_library( LAPACK_LIBRARIES NAMES lapack )
    	endif()
    endif()
endif()
